# Generated by Django 2.0.1 on 2018-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blurb', models.TextField(blank=True)),
                ('num_pages', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
