# Generated by Django 2.0.1 on 2018-03-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180317_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion_model',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%Y %H/%M/%S'),
        ),
    ]
