# Generated by Django 2.0.1 on 2018-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180326_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion_model',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
