# Generated by Django 2.0.1 on 2018-03-27 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180327_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion_model',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
