# Generated by Django 2.0.1 on 2018-04-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180405_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion_model',
            name='author',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
