# Generated by Django 2.0.1 on 2018-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_suggestion_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
