# Generated by Django 2.0.1 on 2018-04-12 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20180411_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_model',
            old_name='interests',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='student_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
