# Generated by Django 2.0.1 on 2018-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20180412_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='image',
            field=models.ImageField(blank=True, max_length=144, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='image_description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
