# Generated by Django 2.0.1 on 2018-04-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_chat_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_model',
            name='updated',
        ),
    ]
