# Generated by Django 2.0.1 on 2018-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_chat_model_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='image',
            field=models.ImageField(blank=True, default='uploads/2018/04/17/default_profile_pic.jpg', max_length=144, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
